name: Test
 
on:
  push:
    branches:
      - main
  pull_request:
 
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: check smth
        uses: actions/checkout@v3
 
      - name: Checkout database
        run: |
          docker compose up -d
          echo "waiting"
          sleep 33
      - name: check api
        run: docker compose exec -it web curl localhost:5000
 
      - name: shutdown docker compose
        if : always()
        run: docker compose down
